# Generated by Django 2.2.7 on 2020-10-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Appl_Route',
            fields=[
                ('key_appl_route', models.AutoField(primary_key=True, serialize=False)),
                ('appl_route_text', models.CharField(max_length=200, verbose_name='応募経路')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_Department',
            fields=[
                ('key_index', models.AutoField(primary_key=True, serialize=False)),
                ('headquarters_text', models.CharField(max_length=100, verbose_name='本部')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_Judgment',
            fields=[
                ('key_judgment', models.AutoField(primary_key=True, serialize=False)),
                ('judgment_text', models.CharField(max_length=100, verbose_name='判定内容')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_Work_History',
            fields=[
                ('key_history_kbn', models.AutoField(primary_key=True, serialize=False)),
                ('work_history_kbn', models.CharField(max_length=100, verbose_name='経歴区分')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T_Applicant_info',
            fields=[
                ('key_applicant', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_date', models.DateField(verbose_name='応募日')),
                ('applicant_no', models.CharField(max_length=20, verbose_name='応募者No')),
                ('applicant_name_text', models.CharField(max_length=100, verbose_name='応募者名')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('key_appl_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Appl_Route', verbose_name='応募経路')),
                ('key_history_kbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Work_History', verbose_name='経歴区分')),
            ],
        ),
        migrations.CreateModel(
            name='T_Judgment',
            fields=[
                ('key_judgment', models.AutoField(primary_key=True, serialize=False)),
                ('judgment_index', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='優先順位')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('judgment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Judgment', verbose_name='面談実施判定')),
                ('key_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantctl.T_Applicant_info', verbose_name='応募者情報Key')),
                ('key_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Department', verbose_name='本部')),
            ],
        ),
    ]
