# Generated by Django 2.2.7 on 2020-01-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_applicant_info',
            name='key_appl_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Appl_Route', verbose_name='応募経路'),
        ),
    ]
