# Generated by Django 3.0 on 2020-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0002_auto_20200106_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_applicant_info',
            name='upd_cnt',
            field=models.IntegerField(default=0, verbose_name='更新カウンタ'),
        ),
        migrations.AlterField(
            model_name='t_applicant_info',
            name='u_date',
            field=models.DateTimeField(verbose_name='更新日時'),
        ),
    ]
