# Generated by Django 3.0 on 2020-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0003_auto_20200201_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_applicant_info',
            name='u_date2',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
