# Generated by Django 3.0 on 2020-02-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0004_t_applicant_info_u_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_applicant_info',
            name='u_date2',
        ),
    ]
