# Generated by Django 3.0 on 2020-02-02 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0005_remove_t_applicant_info_u_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_applicant_info',
            name='upd_cnt',
        ),
        migrations.AlterField(
            model_name='t_applicant_info',
            name='u_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
    ]
