# Generated by Django 3.0 on 2020-02-09 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0006_auto_20200202_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_judgment',
            name='u_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
    ]
