# Generated by Django 3.0 on 2020-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0007_auto_20200209_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_judgment',
            name='u_date',
            field=models.CharField(max_length=100, verbose_name='更新者a'),
        ),
    ]
